package net.mahdilamb.charts.rtree;

/**
 * Enum for different Rtree bulk loaders
 */
public enum BulkLoader {
    /**
     * Sort the leaves by the mid-x component and merge nodes upwards (can be useful for point data, otherwise not
     * recommended)
     */
    NEAREST_X,
    /**
     * Sort the leaves by index of hHilbert curve and merge upwards
     */
    HILBERT_SORTED,
    /**
     * Sort the leaves by index of Morton (Z-order curve) and merge upwards
     */
    Z_ORDER_SORTED,
    /**
     * Sort the leaves by x and y, and merge upwards
     */
    SORT_TILE_RECURSIVE,
    /**
     * Sort the leaves by x and y, but merge downwards (recommended for most applications)
     */
    OVERLAP_MINIMIZING_TOPDOWN;

    /**
     * @param tree  the tree to insert into
     * @param items the nodes to insert
     * @param <T>   the type of data in the nodes
     * @return a new root node of the subtree generated by the items
     */
    <T> RectangularNode<T> bulkLoad(AbstractRTree<T> tree, Node2D<T>[] items) {
        switch (this) {
            case OVERLAP_MINIMIZING_TOPDOWN:
                return BulkLoaders.OMT(tree.minEntries, tree.maxEntries, items);
            case SORT_TILE_RECURSIVE:
                return BulkLoaders.STR(tree.maxEntries, items);
            case HILBERT_SORTED:
                return BulkLoaders.HilbertSorted(tree.maxEntries, items);
            case Z_ORDER_SORTED:
                return BulkLoaders.ZOrderSorted(tree.maxEntries, items);
            case NEAREST_X:
                return BulkLoaders.NearestXSorted(tree.maxEntries, items);
            default:
                throw new UnsupportedOperationException(this + " is not currently implemented");
        }
    }
}
